# R for travis documentation: https://docs.travis-ci.com/user/languages/r

language: r
r: bioc-devel

cache: packages

sudo: false
# Strict checks in place
warnings_are_errors: false

branches:
  only:
    - master
    - cache

bioc_packages:
  - BiocGenerics
  - BiocCheck
  - GenomeInfoDb
  - GenomicRanges
  - GenomicDataCommons
  - IRanges
  - MultiAssayExperiment
  - RTCGAToolbox
  - SummarizedExperiment
  - S4Vectors
  - BiocStyle
  - curatedTCGAData

# Test code coverage
r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'library(covr);codecov()'
  - R CMD BiocCheck --new-package --no-check-vignettes TCGAutils*.tar.gz
